ALTER TABLE COUNTRIES 
    ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY ( COUNTRY_ID ) ;
	
ALTER TABLE DEPARTMENTS 
    ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY ( DEPARTMENT_ID ) ;
	
ALTER TABLE EMPLOYEES 
    ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY ( EMPLOYEE_ID ) ;

ALTER TABLE EMPLOYEES 
    ADD CONSTRAINT EMP_EMAIL_UK UNIQUE ( EMAIL ) 
;

ALTER TABLE JOBS 
    ADD CONSTRAINT JOB_ID_PK PRIMARY KEY ( JOB_ID ) ;
	
ALTER TABLE JOB_HISTORY 
    ADD CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY ( EMPLOYEE_ID, START_DATE ) ;
	
ALTER TABLE LOCATIONS 
    ADD CONSTRAINT LOC_ID_PK PRIMARY KEY ( LOCATION_ID ) ;
	
ALTER TABLE REGIONS 
    ADD CONSTRAINT REG_ID_PK PRIMARY KEY ( REGION_ID ) ;



ALTER TABLE COUNTRIES 
    ADD CONSTRAINT COUNTR_REG_FK FOREIGN KEY 
    ( 
        REGION_ID
    ) 
    REFERENCES REGIONS 
    ( 
        REGION_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE DEPARTMENTS 
    ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY 
    ( 
        LOCATION_ID
    ) 
    REFERENCES LOCATIONS 
    ( 
        LOCATION_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE DEPARTMENTS 
    ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY 
    ( 
        MANAGER_ID
    ) 
    REFERENCES EMPLOYEES 
    ( 
        EMPLOYEE_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE EMPLOYEES 
    ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY 
    ( 
        DEPARTMENT_ID
    ) 
    REFERENCES DEPARTMENTS 
    ( 
        DEPARTMENT_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE EMPLOYEES 
    ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY 
    ( 
        JOB_ID
    ) 
    REFERENCES JOBS 
    ( 
        JOB_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE EMPLOYEES 
    ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY 
    ( 
        MANAGER_ID
    ) 
    REFERENCES EMPLOYEES 
    ( 
        EMPLOYEE_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE JOB_HISTORY 
    ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY 
    ( 
        DEPARTMENT_ID
    ) 
    REFERENCES DEPARTMENTS 
    ( 
        DEPARTMENT_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE JOB_HISTORY 
    ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY 
    ( 
        EMPLOYEE_ID
    ) 
    REFERENCES EMPLOYEES 
    ( 
        EMPLOYEE_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE JOB_HISTORY 
    ADD CONSTRAINT JHIST_JOB_FK FOREIGN KEY 
    ( 
        JOB_ID
    ) 
    REFERENCES JOBS 
    ( 
        JOB_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE LOCATIONS 
    ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY 
    ( 
        COUNTRY_ID
    ) 
    REFERENCES COUNTRIES 
    ( 
        COUNTRY_ID
    ) 
    NOT DEFERRABLE 
; 
