name: Add Badges
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: add badges
        uses: rocktimsaikia/badge-it@master
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_BADGES }}
          badges: 'gh_license, gh_version, gh_stars'
          badge-style: 'flat-square'
